FROM node:18.7.0-slim

WORKDIR /build

COPY app/ src/
COPY public/ ./public
COPY package.json package-lock.json ./

RUN npm install -g npm@latest
RUN npm install --omit=dev
RUN npm run build
