FROM golang:alpine3.17

WORKDIR /parser

RUN addgroup parser && adduser -D -h /parser -G parser parser
RUN chown -R parser /parser && chmod -R 750 /parser
USER parser

RUN mkdir secret
COPY secret/steam_credentials.txt secret/.
COPY parser/go.mod parser/go.sum  ./
RUN go mod download

COPY parser/. .
RUN go build -o run

CMD [ "./run" ]
